# Numpy
## Ejercicios prácticos

---
### Utiliza Python y Numpy para realizar las siguientes operaciones:
1. Dado el arreglo `a = np.array([1, 2, 3, 4])`, determina si ninguno de los elementos es cero.
2. Dado el arreglo `a = np.array([0, 0, 2, 0])`, determina si contiene algún elemento que no sea cero.
3. Analiza el arreglo `a = np.array([1, 2, np.nan, np.inf])` y determina si contiene valores que sean infinitos o valores no numéricos (NaN).
4. Dado el arreglo `a = np.array([1, 2, np.inf])`, determina si contiene valores infinitos.
5. Dado el arreglo `a = np.array([1, np.nan, 3])`, determina si contiene valores NaN.
6. Dados los arreglos `a = np.array([1, 3, 5])` y `b = np.array([2, 3, 4])`, realiza una comparación elemento a elemento contemplando mayor, mayor o igual, menor y menor o igual.
7. Crea un arreglo que contenga los valores 1, 7, 13 y 105, y determina la cantidad de memoria que ocupa el arreglo.
8. Crea un arreglo de 10 ceros; uno de 10 unos; y uno de 10 cincos.
9. Crea un arreglo que contenga todos los números enteros entre 30 y 70.
10. Crea un arreglo que contenga los números pares entre 30 y 70.
11. Crea una matriz identidad de 3x3.
12. Genera un número aleatorio entre 0 y 1.
13. Crea un arreglo de 15 números aleatorios tomados de una distribución normal estándar.
14. Crea un arreglo con valores entre 15 y 55, e imprime todos los valores excepto el primero y el último.
15. Crea un vector (arreglo) de longitud 10 con valores equitativamente distribuidos entre 5 y 50.
16. Crea un vector con valores de 0 a 20, y cambia el signo de los números de 9 a 15.
17. Convierte el arreglo `a = np.array([1, 2, 3])` a una lista de Python.
18. Convierte la lista `l = [1, 2, 3]` a un arreglo de Numpy.
19. Dada la matriz `m = np.array([[1, 2], [3, 4]])`, verifica qué números son pares y almacena los resultados en otra matriz.
20. Dado el arreglo `m = np.array([[1, 2, 3], [4, 5, 6]])`, encuentra el número de filas y columnas de la matriz.

In [1]:
import numpy as np

In [7]:
# ejercicio 1
a = np.array([1, 2, 3, 4])
print("1. ¿Ningún elemento es cero?:", np.all(a != 0))

1. ¿Ningún elemento es cero?: True


In [8]:
# ejercicio 2
a = np.array([0, 0, 2, 0])
print("2. ¿Contiene algún elemento distinto de cero?:", np.any(a != 0))

2. ¿Contiene algún elemento distinto de cero?: True


In [9]:
# ejercicio 3
a3 = np.array([1, 2, np.nan, np.inf])
print("3. ¿Contiene NaN o Inf?:", np.any(np.isnan(a3) | np.isinf(a3)))

# ejercicio 4
a4 = np.array([1, 2, np.inf])
print("4. ¿Contiene valores infinitos?:", np.any(np.isinf(a4)))

# ejercicio 5
a5 = np.array([1, np.nan, 3])
print("5. ¿Contiene NaN?:", np.any(np.isnan(a5)))

# ejercicio 6
a6 = np.array([1, 3, 5])
b6 = np.array([2, 3, 4])
print("6. Comparaciones:")
print("Mayor:", a6 > b6)
print("Mayor o igual:", a6 >= b6)
print("Menor:", a6 < b6)
print("Menor o igual:", a6 <= b6)

# ejercicio 7
a7 = np.array([1, 7, 13, 105])
print(f"7. Tamaño en memoria: {a7.nbytes} bytes")

# ejercicio 8
print("8. Ceros:", np.zeros(10), "Unos:", np.ones(10), "Cincos:", np.full(10, 5))

# ejercicio 9
print("9. Rango 30-70:", np.arange(30, 71))

# ejercicio 10
print("10. Pares 30-70:", np.arange(30, 71, 2))

# ejercicio 11
print("11. Matriz identidad 3x3:\n", np.eye(3))

# ejercicio 12
print("12. Aleatorio 0-1:", np.random.random())

# ejercicio 13
print("13. 15 aleatorios (normal):", np.random.randn(15))

# ejercicio 14
a14 = np.arange(15, 56)
print("14. Valores excepto primero y último:", a14[1:-1])

# ejercicio 15
print("15. 10 valores equitativos (5-50):", np.linspace(5, 50, 10))

# ejercicio 16
a16 = np.arange(21)
a16[9:16] *= -1
print("16. Cambio de signo 9-15:", a16)

# ejercicio 17
a17 = np.array([1, 2, 3])
print("17. Convertido a lista:", a17.tolist())

# ejercicio 18
l18 = [1, 2, 3]
print("18. Convertido a Numpy:", np.array(l18))

# ejercicio 19
m19 = np.array([[1, 2], [3, 4]])
pares = m19 % 2 == 0
print("19. Máscara de pares:\n", pares)

3. ¿Contiene NaN o Inf?: True
4. ¿Contiene valores infinitos?: True
5. ¿Contiene NaN?: True
6. Comparaciones:
Mayor: [False False  True]
Mayor o igual: [False  True  True]
Menor: [ True False False]
Menor o igual: [ True  True False]
7. Tamaño en memoria: 32 bytes
8. Ceros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] Unos: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] Cincos: [5 5 5 5 5 5 5 5 5 5]
9. Rango 30-70: [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]
10. Pares 30-70: [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]
11. Matriz identidad 3x3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
12. Aleatorio 0-1: 0.9380968379404789
13. 15 aleatorios (normal): [ 1.21913603  1.03953401 -0.01293045 -0.30117512 -0.67766947 -0.01831843
  0.24384415  0.0915821   0.33267889  1.11053485 -1.05304947  1.09441649
 -1.78360804  1.66843212 -0.06805182]
14. Valores excepto primero y último: [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 

In [10]:
# ejercicio 20
m = np.array([[1, 2, 3], [4, 5, 6]])
filas, columnas = m.shape
print(f"20. Filas: {filas}, Columnas: {columnas}")

20. Filas: 2, Columnas: 3
